version: 2
jobs:
  deploy:
    docker:
      - image: docker:17.12.1-ce-git
    steps:
      - checkout:
          path: ~/repo
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
              cp /tmp/workspace/example .
              echo $DOCKER_PASSWORD | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker build -t "buckleywdavid/producer-consumer:$CIRCLE_SHA1" -t "buckleywdavid/producer-consumer:latest" .
              docker push "buckleywdavid/producer-consumer:$CIRCLE_SHA1"
              docker push "buckleywdavid/producer-consumer:latest"
          name: "Build and Deploy Docker Image"
    working_directory: ~/repo/app
  build:
    docker:
      - image: golang
    steps:
      - checkout:
          path: ~/repo
      - run:
          command: |
            make build
      # Persist the specified paths (workspace/echo-output) into the workspace for use in downstream job. 
      - persist_to_workspace:
          root: bin
          # Must be relative path from root
          paths:
            - example
    working_directory: ~/repo/app
workflows:
  version: 2
  nats:
    jobs:
      - build
      - deploy:
          requires:
            - build

