---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsstreamingclusters.streaming.nats.io
spec:
  group: streaming.nats.io
  names:
    kind: NatsStreamingCluster
    listKind: NatsStreamingClusterList
    plural: natsstreamingclusters
    singular: natsstreamingcluster
    shortNames: ["stanclusters", "stancluster"]
  scope: Namespaced
  version: v1alpha1
---
apiVersion: v1
kind: Namespace
metadata:
  name: nats-io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nats-streaming-operator
  namespace: nats-io
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nats-streaming-operator
  namespace: nats-io
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-streaming-operator
  template:
    metadata:
      labels:
        name: nats-streaming-operator
    spec:
      serviceAccountName: nats-streaming-operator
      containers:
      - name: nats-streaming-operator
        image: synadia/nats-streaming-operator:v0.1.0-v1alpha1
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nats-io:nats-streaming-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nats-io:nats-streaming-operator
subjects:
- kind: ServiceAccount
  name: nats-streaming-operator
  namespace: nats-io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nats-io:nats-streaming-operator
rules:
# Allow creating CRDs
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs: ["*"]

# Allow all actions on NatsClusters
- apiGroups:
  - nats.io
  resources:
  - natsclusters
  - natsserviceroles
  verbs: ["*"]

# Allow all actions on NatsStreamingClusters
- apiGroups:
  - streaming.nats.io
  resources:
  - natsstreamingclusters
  verbs: ["*"]

# Allow actions on basic Kubernetes objects
- apiGroups: [""]
  resources:
  - configmaps
  - secrets
  - pods
  - services
  - serviceaccounts
  - serviceaccounts/token
  - endpoints
  - events
  verbs: ["*"]
